# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: johngardner.name
email: hello@eyebolt.com
description: > # this means to ignore newlines until "baseurl:"
  If I'm not swamped, this site will contain a list of what I've been working on
  recently.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johngardner.name" # the base hostname & protocol for your site
twitter_username: huxoll
github_username:  huxoll

# Build settings
markdown: kramdown
